### ISSUE TITLE
Find access to quadriflow executables

### ISSUE THREAD

**Issue by norgeotloic** [norgeotloic/BakeMyScan#31]

**Comment by filibis** [comment]
Hi Loïc, I find [this thread](https://blenderartists.org/t/quadriflow-remesher/1132946) on Blender, there user [ambi](https://blenderartists.org/u/ambi) shared [quadriflow binaries (addon)](https://gumroad.com/l/PMwVB). I'm hoping that's useful somehow (:

**Comment by norgeotloic** [comment]
Thanks for your suggestion! I've been discussing with tintwotin who also provided this link, which I did not take the time to check yet... There's also [this issue](https://github.com/hjwdzh/QuadriFlow/issues/22) on Quadriflow's github, which could provide us some hope ;)

**Comment by norgeotloic** [comment]
cf the issue on Quadriflow's github repository, I close this issue.
