### ISSUE TITLE
Connect to Assert-Flinger? 

### ISSUE THREAD

**Issue by tin2tin** [norgeotloic/BakeMyScan#4]
I don't know if you know this add-on, but it seems to me that what you're doing here might be a match made in heaven with Assert-Flinger: https://github.com/black-h0bB1T/Asset-Flinger :-)

**Comment by loicNorgeot** [comment]
Thanks for th link, I'll definitely have a look as this indeed might be nice to interface with collections of remeshed assets!

**Comment by norgeotloic** [comment]
Thanks for the link, I'll definitely have a look as this indeed might be nice to interface with collections of remeshed assets!

**Comment by tin2tin** [comment]
Your add-on may actually be a solution for an old dream of mine(if I can get the add-on to work), to make a previz/animatic/storyboard asset pack: https://blenderartists.org/t/creating-a-collaborative-previz-assets-pack/700383 Which can be used with https://www.youtube.com/watch?v=AG52ytTa_JU :-)

**Comment by norgeotloic** [comment]
Good idea with this kind of plugin.
I'll have a few thoughts about it too, as I programmed with Blend4Web in the past which seems perfect to implement an online library of objects searchable through javascript and probably "interfacable" within blender. What's more, github provides a free and easy way to host such a javascript application and assets (if they are in light formats such as .stl) and manage the lowpoly assets (did you check [this model](https://skfb.ly/6zqCE)?) in a perfect way for collaborative / review the assets before posting / propose pull requests to integrate new collections...
You had my curiosity, now you have my interest!
I'll get in touch with you in the coming days!

**Comment by tin2tin** [comment]
Did a previz test with some of your low-poly characters, added to the scene with asset-flinger(need to figure out how to find the right size, before converting into assets): https://www.youtube.com/watch?v=oIjY5uHu_l0 Thank you for the low-poly characters. :-)

**Comment by norgeotloic** [comment]
Hey @tin2tin, long time !

I've make a lot of things evolve with BakeMyScan and other associated projects I'll be working on (some of them are available [here](https://github.com/norgeotloic/BakeMyScan/projects)).

I'm closing this issue as this is a mid to long-term feature and I'll keep the issues page for the "day to day" issues, but this is definitely something I'll implement!

I'll keep my "todo" and ideas about it on [this github project](https://github.com/norgeotloic/BakeMyScan/projects/4), and I'll make sure to let you know and ask you for advices/ideas when I'll start tackling this project.
