### ISSUE TITLE
Integration with openMVS

### ISSUE THREAD

**Issue by AndreaMonzini** [norgeotloic/BakeMyScan#56]
Hello!
thank you for your great addon!
I will test it as soon as possible.

I use openMVG + openMVS for photogrammetry.
https://github.com/openMVG/openMVG
https://github.com/cdcseacave/openMVS

I read in the roadmap a possible integration with OpenMVS.
Could it be possible to integrate OpenMVG and OpenMVS with BakeMyScan?
A Blender Addon with photogrammetry scan,  remeshing, retopology and PBR textures management  would be super!

As reference there is this useful addon
https://github.com/cogitas3d/OrtogOnBlender

Thank you,
Andrea

**Comment by norgeotloic** [comment]
Hi there, and thanks for your inquiry!
Sorry if the plan is not "definitive" yet, as I'm still creating content and fixing the last bugs in the actual version of BMS...
I actually tried OpenMVG + OpenMVS also, which worked fine for me, but seemed to get better results with Colmap ;). But when I'll start putting the scripts I use into the addon, I'll definitely add OpenMVG o my TODO list.

However, I cannot provide you with much more information concerning the "when" aspect right now, as I'll be defining an "official" roadmap in the next few days / weeks, so make sure to stay tuned!

I'm sure BakeMyScan can quickly turn into something great though, so if you have any feedback, I would absolutely love to have it (right now, you would be the 2nd person ever giving me feedback ;) ).

Keeping this issue opened, and marking as a "duplicate" of colmap+openmvs for reference!

**Comment by norgeotloic** [comment]
You're very welcome!
I'll might ping you in a mid-term future to exchange about the workflow you use for scanning, and will see what I can do!
Something funny: I did not even know about Blender GPL Python compliance, I guess I've just been lucky on that one ;)
I'll be waiting for your feedback, and do not worry if I might take some time to answer in the future, as I'm currently setting up the website/tutorials/documentation/roadmap/bugfixing/donation/communication/community aspect of it all !
